[package]
name = "quadtree"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "2.2.0"
image = "0.25.5"
tempfile = "3.14.0"
wayland-client = "0.31.7"
wayland-protocols = { version = "0.32.5", features = ["client", "wayland-client"] }
